### ISSUE TITLE
shift / ctrl clicking 

### ISSUE THREAD

**Issue by seiyria** [angular-ui/ui-sortable#205]
Is this a feature that could be added to ui-sortable, or should it just be added on top as a separate component?

**Comment by timediv** [comment]
Will this extension still be considered for the main project?

**Comment by thgreasi** [comment]
In it's current state, I would prefer having ui-sortable to be just a jquery-ui-sortable wrapper and as slim as possible.
This way the main branch code can be more maintainable but it will also have to expose enough hooks to provide more complex interactions.

Merging the multi-selection interaction, would also need lots of extra test, that I have yet to write for ui-sortable-multiselection.
Maybe at a later time, if some refactoring to the multi-selection code is done so that it looks similar to the code in the main branch.

**Comment by chrismhinsch** [comment]
This is great! I just implemented this into my project and it does exactly what I want it to do. Thanks :)
