### ISSUE TITLE
bug when using track by $index

### ISSUE THREAD

**Issue by vertazzar** [angular-ui/ui-sortable#290]
Hi guys, thanks for making this very simple and awesome implementation of jquery ui sortable into angular!

These last 2 days I've been working with this code and I realised that when you use item in items track by $index expression for ng-repeat, the sorting behaviour of HTML is acting weird...

see the full example here
http://codepen.io/anon/pen/ECgxb

the example shows that if you add classes or any html attribute directive (see the directive "barFar", which simply adds far or bar based on $index) the item that gets dropped "inherits" the same classes as the item on which it was dropped to, so if your item 1 is red, and item 2 is green (the one that you are dragging) upon dropping it on item 1, it will be come red bordered.

this is solved by using standard "item in items", but sometimes you may have dupes https://docs.angularjs.org/error/ngRepeat/dupes and you need the expression track by $index

I know that in readme it states that the index must match the dom, which essentially in this case is the truth, it just that it weirdly behaves regarding the html rendering

**Comment by thgreasi** [comment]
@vertazzar any feedback?
Based on the [aforementioned AngularJS comment](https://github.com/angular/angular.js/issues/7119#issuecomment-40572773), I'm closing this for now.

I really think that the models should be representative of the final view.
The code should expect that a complete view relinking/rerendering might happen at any time and should handle that appropriately.
I would suggest you to add an extra property to your model and fill it on the first load, instead of expecting that the DOM elements will stay intact and hold their state.

I would be more comfortable with [something like this](http://codepen.io/anon/pen/qEqjaX) but I still can't figure out the `track by $index` issue.

Thanks for the proper reporting and in case you got any extra insight, I would love it if you could share it here.
