### ISSUE TITLE
beforeStart callback?

### ISSUE THREAD

**Issue by Kuzmin** [angular-ui/ui-sortable#328]
Hello again,

Is it possible to add a beforeStart callback before plugin initialization? I currently have some divs that need to be shown only when dragging (you are supposed to drop items in them), but if I show them at the `start` event, the plugin has already initialized, and these boxes don't get any ui-sortable functionality.

I think that a sync function, beforeStart, that could be called before the plugin initializes itself should do the trick. 

(I read the source code and it seems like the plugin is initialized before the start callback, I also looked at using the `create` callback, or using `ui.helper.refresh()`, but neither of those worked.)

Sorry if this turns out to be as stupid a request as the last one I posted.

**Comment by thgreasi** [comment]
You might want to take a look at #324 since it sounds somewhat similar.

Since this directive hooks on the jquery-ui-sortable's callbacks, I can't think a clean way to add such a callback.
If something is achievable with jquery-ui-sortable then it should be achievable with the ui-sortable directive.

Other than the older issue (#324), I can only suggest you to use [start](http://api.jqueryui.com/sortable/#event-start). Anyway [ui-sortable does not do anything serious in the start callback](https://github.com/angular-ui/ui-sortable/blob/3a8dff154acf2149fd73578cf87da6db62f563f0/src/sortable.js#L107), so I don't think  a beforeStart callback could add any value.
