### ISSUE TITLE
(enh) still allow jQLite to be used elsewhere

### ISSUE THREAD

**Issue by evadne** [angular-ui/ui-sortable#335]
Made the following small change that allows me to continue using jQLite in other parts of the application.

	17,18c17,18
	<         link: function(scope, inElement, attrs, ngModel) {
	<           var savedNodes, selector = (jQuery || angular.element), element = selector(inElement);
	---
	>         link: function(scope, element, attrs, ngModel) {
	>           var savedNodes;
	87c87
	<           if (!selector.fn || !selector.fn.jquery) {
	---
	>           if (!angular.element.fn || !angular.element.fn.jquery) {
	112c112
	<                 var sortableWidgetInstance = getSortableWidgetInstance(selector(e.target));
	---
	>                 var sortableWidgetInstance = getSortableWidgetInstance(angular.element(e.target));
	161c161
	<                 phElement = selector(phElement);
	---
	>                 phElement = angular.element(phElement);

**Comment by thgreasi** [comment]
Is there a special use case that this can be beneficial? (Since jQlite is a subset of jQuery.)
Is this so that you can load jQuery after angular?

When jQuery is not used by angular.element, in case angular removes a node that has jQuery event handlers attached to it then jQlite will not properly clear those handlers (and possibly the data-* cache) possibly causing a memory leak.

**Comment by thgreasi** [comment]
@evadne any feedback on this?

**Comment by thgreasi** [comment]
@evadne any feedback on this?

**Comment by evadne** [comment]
You are correct on the use case, IMHO if there is another destruction hook we can clean up things there?

**Comment by thgreasi** [comment]
1. I'm against re-implementing things that jQuery already does (its own cleanups). At least, not in the master branch.
2. I can't find a reason to provide such implementation, given that AngularJS developers have already put some effort to **prefer** jQuery instead of jQlite, if it is loaded first.
3. If we indeed provide such an implementation, then it would be just one directive not causing memory leaks of that type.

**Comment by thgreasi** [comment]
> Is there a special use case that this can be beneficial? (Since jQlite is a subset of jQuery.)
> Is this so that you can load jQuery after angular?
