### ISSUE TITLE
Receive new item

### ISSUE THREAD

**Issue by forza020** [angular-ui/ui-sortable#336]
Hello,

First of all, thank you for your wonderful directive. Just wondering any plans to make it work in conjunction with jQuery draggable? I'm speaking about situation when sortable list receives new element. http://jqueryui.com/draggable/#sortable

Thank you.

**Comment by thgreasi** [comment]
I have never experiment with that integration use case.
BUT, you can surely use a single item sortable instead of a draggable directive.
Take a look at the [Cloning example in README](http://codepen.io/thgreasi/pen/qmvhG) since by default the sorting will remove the items from its original list.

If the ingredients list is split into several single item sortable directive, then the result will be very similar to the draggable-sortable interaction you described.
