### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by tgrant54** [angular-ui/ui-sortable#351]
jQuery version: 2.1.3
jQuery-UI version: 1.10.4
angular version: 1.2.18
ui-sortable version: 0.13.3

Here is the callstack:

    Sizzle.attr	@	jquery.js:1446
    Sizzle.selectors.filter.ATTR	@	jquery.js:1642
    i	@	jquery.js:2143
    superMatcher	@	jquery.js:2361
    Sizzle.select	@	jquery.js:2531
    Sizzle	@	jquery.js:850
    jQuery.event.handlers	@	jquery.js:4475
    jQuery.event.dispatch	@	jquery.js:4412
    jQuery.event.add.elemData.handle	@	jquery.js:4116
    jQuery.extend.buildFragment	@	jquery.js:5145
    jQuery.fn.extend.domManip	@	jquery.js:5382
    jQuery.fn.extend.append	@	jquery.js:5213
    jQuery.each.jQuery.fn.(anonymous function)	@	jquery.js:5458
    angular.module.value.directive.link.callbacks.update	@	sortable.js:214
    (anonymous function)	@	sortable.js:25
    $.Widget._trigger	@	jquery-ui.js:785
    $.widget._trigger	@	jquery-ui.js:4783
    (anonymous function)	@	jquery-ui.js:401
    (anonymous function)	@	jquery-ui.js:4702
    $.widget._clear	@	jquery-ui.js:4772
    (anonymous function)	@	jquery-ui.js:401
    $.widget._mouseStop	@	jquery-ui.js:3958
    (anonymous function)	@	jquery-ui.js:401
    $.widget._mouseUp	@	jquery-ui.js:958
    (anonymous function)	@	jquery-ui.js:401
    $.widget._mouseDown._mouseUpDelegate	@	jquery-ui.js:914
    jQuery.event.dispatch	@	jquery.js:4430
    jQuery.event.add.elemData.handle	@	jquery.js:4116

I look into this issue a bit and found a simple workaround located at: http://www.ciiycode.com/0SHByPqgXqeg/ngrepeat-sorting-is-throwing-an-exception-in-jquery

workaround:

    Object.getPrototypeOf(document.createComment('')).getAttribute = function() {}

I am only getting this error when I am sorting. I am not 100% sure if this is a problem with Angular or this directive.

**Comment by thgreasi** [comment]
@tgrant54 Hi there!

I just tried to run all the e2e tests with the exact versions of the libraries that you reported and everything passed.

I would be very interested to take a look in an example code (codepen/fiddle/...). Is there any chance that you can create one by the weekend?

After following the link you posted, I would like to ask you if you apply any filters on the `ng-repeat`.
If thats the case, then please follow one of the ordering/filtering [examples as found in README.md](https://github.com/angular-ui/ui-sortable#examples).
Unfortunately using a filter on the `ng-repeat` (as discussed in lots of other issues) is not allowed, since it would break the sync of the `ng-model` and the generated DOM elements.
The examples found in README shows how to do the filtering in the controller (which by the way is more efficient).

**Comment by tgrant54** [comment]
@thgreasi thanks for the reply.

I will try and get an example setup tomorrow when I return to work and I will get back to you ASAP.

**Comment by tgrant54** [comment]
@thgreasi 

I have made a jsfiddle... however I was unable to replicate the error. 

https://jsfiddle.net/tgrant54/sr6hafs9/

Would you be willing to take a look at the live code where I am getting the error?

**Comment by thgreasi** [comment]
Point me out to a url and a file path and I might find some time in the
weekend for this.

**Comment by thgreasi** [comment]
Just keep in mind (in case that you missed it) that you can only have one `ng-repeat` inside the `[ui-sortable]` element.

**Comment by tgrant54** [comment]
Can you please send me a quick email at - tyler[at]grantcr.com 

I am working on a webapp and I do not wish to disclose the link publicly. I will go ahead an setup a test account and will give you the information through email.
