### ISSUE TITLE
Sortable update() callback

### ISSUE THREAD

**Issue by toncid** [angular-ui/ui-sortable#352]
Hello,

It seems that the `update` event is fired before the DOM is updated. Please check this example: http://codepen.io/anon/pen/MwgPwW

If you move "Item 6" to the position of "Item 1", in the `update` callback the `ui.item.nextAll()` method returns siblings relative to the original position (i.e. an empty set) and not relative to the new position (i.e. five other elements). 

This is opposite from what the documentation indicates:

> `update` is the appropriate place to cancel a sorting, since it occurs before any model/scope changes but after the DOM position has been updated. [...]

Is this expected? Thanks!

**Comment by toncid** [comment]
The issue doesn't seem to be reproducible when using the Sortable directly (i.e. outside AngularJS): http://plnkr.co/edit/FMWQSDXMyHr9XtLFmj0J?p=preview

**Comment by thgreasi** [comment]
Hi @toncid,
That's because inside the `update` callback we cancel the sorting and do it by changing the position of the items inside the model array (AKA "the angular way").
I'm sorry if this caused any problems to you, but this change was required in order to support angularjs v1.2+.
But as you can see in [API.md](https://github.com/angular-ui/ui-sortable/blob/master/API.md) we provide properties like `index` (the original index of the item) and `dropindex` for you to use. Ideally you should not have to access DOM nodes directly and apply your logic on the model and these extra properties of the `ui.item.sortable` object.

**Comment by thgreasi** [comment]
If you find any extra property you would like to be exposed, feel free to open a new issue.

**Comment by toncid** [comment]
Thanks for the explanation. 

I did see this documentation file, but what confused me is when I dump the `ui` object in the Dev Tools console (in Chrome), all `sortable` fields appear as undefined. The reason must be some kind of a side effect...

**Comment by thgreasi** [comment]
This was also reported in #346.
> Keep in mind that the properties of ui.item.sortable object are cleared
right after the stop callback fires. (To avoid memory leaks.)

> If you need those references you should keep them in variables in your code.

:smile:

**Comment by thgreasi** [comment]
We should probably add this to the documentation as well...

**Comment by toncid** [comment]
Yup, I thought this was the case. Cannot hurt to add an extra line to avoid confusion.

**Comment by thgreasi** [comment]
Opened an issue for this #353.
Pr's welcome.
