### ISSUE TITLE
Cannot get it to save first sort, all other sorts save just fine. 

### ISSUE THREAD

**Issue by EmptyPockets** [angular-ui/ui-sortable#359]
I'm using ui-sortable with firebase/angularfire to save the data. Here's my setup: 
   
    //set options for ui-sortable
        $scope.sortableOptions = {
            stop: function(event, ui) {
                $scope.userList.forEach(function(todo){
                 todo.sort = $scope.userList.indexOf(todo);
                  $scope.userList.$save(todo);
                });
          },
          axis: 'y'
        }

    <ul ui-sortable="sortableOptions" ng-model="userList">
    <li ng-repeat = "task in userList | orderBy: 'sort'"> 
    </li>
    </ul>

When I try to sort the first time, everything will move back to its original position. If I try to sort again after that everything works great. Any ideas?

**Comment by thgreasi** [comment]
You should not apply filters to `ng-repeat` since (as README states):
> ...Otherwise the index matching of the generated DOM elements and the ng-model's items will break.
**In other words: The items of ng-model must match the indexes of the generated DOM elements.**

Filtering/Ordering should (ng filters in general that manipulate the ng-model) be applied in the controller and not in the view. For more details read the [comments in #70](https://github.com/angular-ui/ui-sortable/issues/70#issuecomment-31612213)

Please refer to the `ordering` and two `filtering` examples found in README on how you should properly apply your logic inside the controller.
