### ISSUE TITLE
"start" event does not update $scope

### ISSUE THREAD

**Issue by Vladimir-Purple** [angular-ui/ui-sortable#360]
http://codepen.io/anon/pen/yNeqqB
Question.

I'm trying to set `$scope.commonVars.started` flag  to `true` when sorting is started, however, as you can see it's stays `false` (look Sorting:false in template), now I found that `$apply` solves it, but take a look at `stop` function, `$scope.sortingLog` is updated without using`$apply`, what I'm missing?

**Comment by thgreasi** [comment]
You are right to be confused.
We currently wrap with apply only the provided stop callback and the model
manipulations that happen internally right before the update, receive and
stop events.

We are not wrapping start, change and update so that
* we minimize the number of digest loops
* avoid possible modifications of the model (eg: from watchers) before the
drop takes place

A model modification while dragging would result the repeater to rerender,
conflicting with the dragging state of the DOM.

As a result, wrapping any provided callback with an apply would not only
hurt performance, but also cause problems to some use cases.

I was considering adding 'ui-start' and 'ui- update' callbacks, that could
be used in case the apply wrapping was required, but I guess that adding
just a note on README would be a better solution. (Less documentation &
connections needed and no code complication.)

What are your thoughts on that?

**Comment by Vladimir-Purple** [comment]
I was not expecting this behaviour but after you described the reason why it's implemented that way it looks reasonable to leave it as is.

Agree, note should be added to README.

**Comment by thgreasi** [comment]
Was hesitant on how to make the reasons clear.
I'm glad, you agree with me.

README note suggestions are welcome.
