### ISSUE TITLE
connectWith Breaks When Scrolled Down

### ISSUE THREAD

**Issue by gkoberger** [angular-ui/ui-sortable#382]
When using `connectWith`, the item is always placed further up the list than it should be when the page is scrolled:

![Example](http://cl.ly/image/082q3c1t1n1g/c)

By moving the item up or down, you can get it to go to the right place. However it makes everything jump initially.

It can be reproduced here: http://angular-ui.github.io/ui-sortable/

If the page isn't scrolled, it works as expected. I cannot reproduce this in jQuery-ui.

**Comment by thgreasi** [comment]
That's really strange, since we are not doing any jquery related action nor any DOM manipulation, before the drop happens and the update event fires. Until update fires it's all jquery-ui-sortable.

If you still have the vanilla jquery-ui example code you mentioned, I would be very interested to do a comparison and try reproduce your findings.

**Comment by gkoberger** [comment]
Ah, seems you're right! The problem seems to be with jQuery UI versions?

1.10.3 (works): http://codepen.io/thgreasi/pen/uFile
1.11.4 (broken): http://codepen.io/gkoberger/pen/PPYPRe
1.11.4 No Angular (broken): http://codepen.io/gkoberger/pen/KdPdoY

I'll file with jQuery-UI :)

**Comment by gkoberger** [comment]
For anyone looking to watch this, I filed a bug against jQuery UI: http://bugs.jqueryui.com/ticket/14404

**Comment by thgreasi** [comment]
:+1:
