### ISSUE TITLE
Model on-way binding possibility?

### ISSUE THREAD

**Issue by sszdh** [angular-ui/ui-sortable#403]
Hi,
Sorry for that kind of question here. but I cant find ant forum for this package so here is my question:

How can we use on-way binding with this directive, something like this:

```html
<ui>
   <li ui-sortable="uiSortableOptions" ng-model="::items" ng-repeat="item in ::items">{{item.title}}</li>
</ui>
```

In fact, I want the variable (`items`) remains unchanged.

Cheers.

**Comment by thgreasi** [comment]
I'm not aware of something like this. The problem is that we are not changing the array itself, but its content.

The simplest thing I can think is to initialize the ng-model to a shallow copy of the list
```js
// inside the controller
$scope.originalItems = $scope.items.slice();
```
and in the view
```html
<ui>
   <li ui-sortable="uiSortableOptions" ng-model="originalItems " ng-repeat="item in originalItems">{{item.title}}</li>
</ui>
```

**Comment by thgreasi** [comment]
Does this suffice as a solution?

**Comment by sszdh** [comment]
The changing array is not problem here but performance. I think if we have a huge array, it will be good to have a option to disable two-way binding as angular have in `ng-repeat`.

Thanks.

**Comment by thgreasi** [comment]
We are actually using the ng-model change detection mechanism to propagate the model changes through the ng-repeat to the DOM.
Otherwise, just use your one-time-binding on the ng-repeat and do not provide a ng-model to the ui-sortable directive.

As of the size of the cloded array (in case that it is a concern for you), it will only require 4bytes per record.

**Comment by thgreasi** [comment]
Also, Huge arrays are bad for UX.

**Comment by sszdh** [comment]
So the answer is NO?
