### ISSUE TITLE
Problem with using ui-sortable and infinite scroll together

### ISSUE THREAD

**Issue by viktor-hunko** [angular-ui/ui-sortable#414]
Hi,
I'm using ui-sortable and infinite scroll and have some problem when items are added dynamically (by infinite scroll). For example, 20 items shown and i'm start dragging element to down so infinite scrolling fires and next 20 items added, and i can't drop element to this new dynamically added items. 
Can someone help me with this issue?
Thanks,

**Comment by thgreasi** [comment]
Hmmm, I've never used it myself, but logically the DOM manipulations from
the infinite scroll probably messes with the sortable implementation. Try
running something like `$(sortableElement).sortable('refresh')` after the
infinite scroll fires.


-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by viktor-nothing** [comment]
Thanks for your answer,
but i tried to do "refresh", and it doesn't help. Problem appear only if the item is added while dragging, and not only by infinite scroll, even if i use, for example some setInterval and add new element each few sec. If we change DOM during the process of dragging without "refresh" - i can't drop dragged element to just added items, but if i do "refresh" after each new added element - it's look strange, elements "flicker".
Here is example with setInterval: http://jsfiddle.net/37nhrp7y/2/
Start dragging and wait till new element will be added and try to drop to the bottom

**Comment by thgreasi** [comment]
Thanks for the great jsfiddle that you provided. Couldn't be more accurate.
I don't think that the problem originates from our side, since the drag&drop functionality is pure jquery-ui-sortable. As a result, I think that this should be reported to jquery-ui-sortable itself.
I also tried [refreshPositions](http://api.jqueryui.com/sortable/#method-refreshPositions) but like  [refresh](http://api.jqueryui.com/sortable/#method-refresh) it didn't work...

**Comment by viktor-hunko** [comment]
I also tried it with pure jquery-ui-sortable, here is example:
http://jsfiddle.net/X5sBm/13/
Seems it works fine after refreshing, this is why i'm asking here

**Comment by thgreasi** [comment]
Thanks for the vanilla jquery-ui version :+1: that was very helpful.
[Here](http://jsfiddle.net/u0p9h8yy/) is how it ended up after some tries.
Some of the things that I had to change included:
* referencing a more recent version of ui-sortable
* using a proper ng-model
* using a better track by (that might not actually be necessary)

Does this cover your use case?

**Comment by viktor-hunko** [comment]
In my project i'm use newest version of jquery-ui and proper ng-model to (just forget about it in jsfiddle above). But unfortunately it's doesn't solve the pb, see video below where elements "blinks" (by the left side - poor jquery-ui, by the right - your example):
https://vimeo.com/148197887

**Comment by thgreasi** [comment]
So, to clear this out, the sorting now works, it's just the blinking that bothers you?

**Comment by viktor-hunko** [comment]
Yep, you're right. I would greatly appreciate it if you are prompt in what direction to look for solving this pb?
Thanks,

**Comment by thgreasi** [comment]
I'm sorry but I really don't know what to suggest, since you absolutely need to refresh the sortable, but this by definition causes the mini reinitialization of jquery-ui-sortable widget and the flickering of the helper and placeholder elements. Your best chance is to dig in jquery-ui documentation.
As you can probably find in other issues, I always have suggested people against manipulating the DOM or the models, during a drag. At this point I'm really happy that it even worked to that degree... Since angular's ngRepeat doesn't like it when you touch the DOM yourself and as an extra we are doing a couple of tricks with the elements that existed at the time that the drag started, so that it can work.

**Comment by viktor-hunko** [comment]
Thank you very much, you've been very helpful! ;)

**Comment by thgreasi** [comment]
It was nice elaborating with you on this. I hope this detailed issue and
its code samples will be useful to others as well. :+1:

-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
