### ISSUE TITLE
Bug with track by $index in nested connected list

### ISSUE THREAD

**Issue by preethi29** [angular-ui/ui-sortable#416]
When ng-repeat is tracked by $index,  moving an element from parent to child list  causes a issue:
**Uncaught Error: cannot call methods on sortable prior to initialization; attempted to call method 'option'**

Issue is reproducible with the tree example provided in README when I moved Item 1 into Item 2 list:

http://codepen.io/anon/pen/mVyGVv

Pleas help asap.

**Comment by thgreasi** [comment]
In such complex use cases, it is highly preferable to track by a unique property, even if it is a dummy id generated by something like `$.guid`. Otherwise you might end up exchanging that scopes of some items (that's probably what happens in your case).
Keep in mind that the different `track by` expressions have a huge difference to how ng-repeat works.

**Comment by preethi29** [comment]
> Otherwise you might end up exchanging that scopes of some items (that's probably what happens in your case)

Can  you explain the cause for this problem here bit more?

**Comment by thgreasi** [comment]
Since this has already been discussed, please take a look at the comments
and the references in issues #290 & #384 . (Especially the last comment in
#290.)

-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Did you find out a working solution for your use case?
I'm closing this for know, since
* a working example exists
* this has already been tracked on other issues
* I don't think that this is the right place to discuss about the inner workings of ng-repeat
