### ISSUE TITLE
ng-repeat | filter:{model}

### ISSUE THREAD

**Issue by oscarvesga** [angular-ui/ui-sortable#427]
Hi all, I have problems using filters in the ng-repeat module. It makes the filter but when I want to move an item from one array to another, put me the wrong index.

**Comment by thgreasi** [comment]
Hi there.
As noted in README and several other issues you have to move your filtering logic in the controller.

> Filters that manipulate the model (like filter, orderBy, limitTo,...) should be applied in the controller instead of the ng-repeat (refer to the provided examples).
This is the preferred way since it:
*    is performance wise better
*    reduces the chance of code duplication
*    is suggested by the angularJS team
*    it does not break the matching of the generated DOM elements and the ng-model's items

You can also take a look at the examples found in README.

**Comment by oscarvesga** [comment]
Ok man, thank you for your early answer
