### ISSUE TITLE
Wrong drop target for nested sortable

### ISSUE THREAD

**Issue by michaschwab** [angular-ui/ui-sortable#431]
Hi! I've been using ng-sortable and it's been working well. Today, we decided to add subfolders to our list, leading to the need to be able to drag items across the hierarchies.

Turns out this is easy because the only place this fails is when ng-sortable tries to find the drop target of the dropped item. It assumes the sortable element is the immediate parent of the item, which is not true if the item is in the nested list. For this reason, the plugin fails at this task, and returns a 'cannot access property ngModel of null' error in the console when trying to drag items across hierarchies, see http://codepen.io/anon/pen/JGgLXQ.

Therefore, in line 188, replacing
`var droptarget = ui.item.parent();`
with
`var droptarget = ui.item.parents('[ui-sortable]');`
will do the trick. This looks for the parent element on which ui sortable was initialized, even if it's not the immediate parent.

Hope this, or a better solution, will be incorporated! Thanks!

**Comment by michaschwab** [comment]
Actually, I'm not sure if this would even allow detecting that is was dropped in the subfolder for my own code, except by looking at the event. Please let me know what you think of this.

**Comment by thgreasi** [comment]
Have you tried the 'Tree' example found in README? How is your
implementation's code compared to that?
As stated in README the items generated by our model have to be immediate
children of your ui-sortable element, so that we can do index matching with
the model array.
Initiating the drag from a nested element can only be achieved using the
'handle' option, but this can't help you with a nested hierarchy use case.
Anyway, we should probably replace the .parent() with
.parent().closest('[ui-sortable]') as a better detection approach.

-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by sszdh** [comment]
Just another suggestion: Use sibling `div` items with left margin assignment to make a fake tree structure :)

**Comment by thgreasi** [comment]
@michaschwab Have you managed to make it work for your use case? Should we mark it as resolved?

**Comment by michaschwab** [comment]
Hi! sorry for not replying earlier. Yes, it works well for me now and we can mark it as resolved. I think I was wrong with some of my assumptions here. Thanks for taking care of this, it's working great.
