### ISSUE TITLE
Mouse cursor on dragging

### ISSUE THREAD

**Issue by AndreasHo** [angular-ui/ui-sortable#438]
Hello,
ich want to use my 2 classes:

`.grabable {
    cursor: -moz-grab;
    cursor: -webkit-grab;
    cursor: grab;
}`
`.grabbing {
    cursor: -moz-grabbing;
    cursor: -webkit-grabbing;
    cursor: grabbing;
}`

when the mouse is over my table (which have ui-sortable) and when one item is dragging. 

When i use ng-class and set a boolean on "start" and change it in "stop" (options) then the two-way-databinding doesn't work :/

Somebody have the same problem? Or have a solution for this problem? :)

Bye Andreas

**Comment by thgreasi** [comment]
It's true that manipulating the element while dragging causes issues to
ui-sortable.
You might get better results if you use the jquery-ui helper option
http://api.jqueryui.com/sortable/#option-helper .
In my experience, the best approach is to use the css class that jQuery-ui
adds (by itself) while dragging. If you really need to add your own css
class, then place it to the (parent/list) ui-sortable element and use a
child css selector for the dragged element.
Let me know any of the above worked for you,  so that we can resolve this.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by AndreasHo** [comment]
on which class i can set my style? the class ui-sortable-helper is to late... the cursor will be changed after dragging for a short time :/

**Comment by thgreasi** [comment]
I just updated the [basic example](http://codepen.io/thgreasi/pen/jlkhr) to use the `ui-sortable-helper` class and I couldn't experience the "changed after dragging for a short time" situation.

I think that this is the most appropriate approach. Can you provide an example of your use case demonstrating the issue that you experience? It might be an issue if your element is not large enough so that jquery-ui can easily constantly place it below your cursor while dragging,

**Comment by thgreasi** [comment]
In case that you need to change the cursor as soon as the click happens (before even starting moving the mouse) then you could [use the `mousedown` event](http://codepen.io/thgreasi/pen/JXRZbZ).

I'm closing this for now. In case that your problem persists, please reopen with an example of your use case (preferably a fork of one of the provided codepen examples).
