### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by cs-NET** [angular-ui/ui-sortable#439]
The jQuery sortable is not destroyed when element is destroyed. Here is a potential fix:

AFTER
```
  // Create sortable
  element.sortable(opts);
```

ADD
```
    element.on('$destroy', function () {
        element.sortable('destroy');
    });
```

**Comment by thgreasi** [comment]
Can you share a memory comparison showcasing the retained memory?
Actually, before releasing v1.3, I did several experiments with the memory efficiency of this directive, including trying the suggested code. Even without it, the memory analysis on chrome showed no leaks. That's probably because, before removing an element from the page (eg a repeater item), jQuery destroys the instantiated plugins and removes all `.data()` assigned values.
If you still think we should add it, please open a PR against the v0.14 branch. The strange thing was that in my tests with the suggested code, the code coverage of the source code dropped !?!?!? Maybe something has changed till now in angular, but the above was denominational.

**Comment by thgreasi** [comment]
Any feedback on this?

**Comment by cs-NET** [comment]
@thgreasi I created a jsFiddle and have **not** been able to reproduce the memory leak I experience in production. In the example the nodes are destroyed and memory is collected as expected. I will try to find some more time to expand on the jsFiddle and see if I can reproduce the issue. 

https://jsfiddle.net/csNET2/fve6kjpx

**Comment by thgreasi** [comment]
Closing this for now.
Please re-open if you find anything more on this.
As an extra, inside the $destroy, I was initially also checking whether the
sortable widget instance still existed before invoking the
`element.sortable('destroy')`.
Thanks for your detailed description on this ticket.

On Sat, Mar 26, 2016 at 7:23 PM Christian Sleight <notifications@github.com>
wrote:

> @thgreasi <https://github.com/thgreasi> I created a jsFiddle and have
> *not* been able to reproduce the memory leak I experience in production.
> In the example the nodes are destroyed and memory is collected as expected.
> I will try to find some more time to expand on the jsFiddle and see if I
> can reproduce the issue.
>
> https://jsfiddle.net/csNET2/fve6kjpx
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/439#issuecomment-201897211>
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
