### ISSUE TITLE
Set a placeholder in nested dropzones

### ISSUE THREAD

**Issue by nelisbraems** [angular-ui/ui-sortable#442]
Hello

My setup has three nested lists that have ui-sortable working on each list. 
A different (non-nested) list of items is used to add items to the nested lists. 
I would like to be able to show a placeholder that's different corresponding to the item that's being dragged. 
Example: item 1 can only dropped onto the first level of nested lists, the placeholder should not be shown on the lower levels. 
I don't have any problems with the sortable behaviour, I would just like to be able to hide a placeholder in some cases. Is there a possibility to do this?

Kindest regards.

**Comment by thgreasi** [comment]
Hi there.
According to my experience, the most performant way to give such visual
feedback is by resulting on css. I ended up defining some css classes that
represent the different types of dragged items (based on the rules that
apply on them). When starting a drag, you should add its representative css
class to the container of the connected sortable and define some descendant
css selectors to hide the placeholders that are not applicable. As a final
step, as an attempt to enforce your policy rules in js code as well, you
should add some checks in the update callback and call the cancel() method
when required.

An other approach would be to change the css selector of the connected
sortables when a drag starts, based on the dragged item. Unfortunately, I'm
afraid that this approach might lead to problems, since it requires
changing the sortable options mid-drag, causing watchers to fire and a
digest cycle.

If you can fork and modify one of the code pens in README to demonstrate
your use case, I could give you a proud of concept.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
