### ISSUE TITLE
Items draggable when they should be locked.

### ISSUE THREAD

**Issue by jaunkst** [angular-ui/ui-sortable#456]
When initially locked you cannot drag an item, after they are unlocked and you drag an item, and then locked them again they are draggable.

http://codepen.io/jaunkst/pen/NNJRxM

**Comment by jaunkst** [comment]
Okay, setting the cancel option with a selector works for me. maybe we should update the example to use that method.

**Comment by thgreasi** [comment]
If I can recall correctly from an other issue that this was discussed, you need to call the [refresh method](https://api.jqueryui.com/sortable/#method-refresh) after changing that option, so that jquery ui notices the change.
Can you try if it works for your use case?
We could possibly make this directive call refresh when such changes to the options happen, but we might end up invoking it more often than needed in case the options are changed one at a time.

Waiting for your feedback!

**Comment by thgreasi** [comment]
Couldn't make it work with `refresh` :(
Posting [this codepen with `cancel`](http://codepen.io/thgreasi/pen/LNazmm) as a reference for others.
Updated the README example to describe the difference of the two approaches:
```js
// The `cancel` option is preferable,
// in case that you are
// updating the item classes on runtime
// eg: adding/removing the `not-sortable` class
// cancel: ".not-sortable"
// The `items` works in case that
// you are not manipulating the items.
// It also prevents us from placing an item
// above "Item 1" or below "Item 6"
items: "li:not(.not-sortable)"
```

Thanks for the detailed report!

**Comment by jaunkst** [comment]
Yep, that's what I ended up doing. =)

**Comment by jesperhansen17** [comment]
By adding the cancel reference saved my day, thanks :)
