### ISSUE TITLE
Production broken since 0.14.1

### ISSUE THREAD

**Issue by mebibou** [angular-ui/ui-sortable#462]
Today I was running test on my app which uses the library, on a virtual machine, fresh install. It wasn't working anymore because it updated from `0.14.0` to `0.14.1` and you moved the production file from the root directory to the `src` folder. I don't think this qualifies as minor change right? maybe you should update to `0.15.0` in this case? I guess many people will have this bad surprise when using `^0.14.0` in their dependcies

**Comment by thgreasi** [comment]
Hi there, sorry for the inconvenience.
Interestingly enough, I wasn't able to find such commit to package.json
during the last release, just updated the version !?
Maybe it's just the dist that might be missing?
I will investigate after work.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
This was probably a bad release manoeuvre, since according to github ([ref 1](https://github.com/angular-ui/ui-sortable/blame/master/package.json) & [ref 2](https://github.com/angular-ui/ui-sortable/commit/456213fa48944221c4a206198b6eb36e577ee764)) the path of the main file hasn't changed since Mar 27, 2014 - src0.12.5 .

Just released v0.14.2 to fix this issue and avoid caching issues.
How are you installing your packages (npm/bower)?

Please re-open if necessary.

**Comment by mebibou** [comment]
Great, looks good now, thanks :)
