### ISSUE TITLE
Enable sortable after condition 

### ISSUE THREAD

**Issue by vitorreis** [angular-ui/ui-sortable#464]
I would like to only enable the sortable after a button be clicked .

```html
<tbody ui-sortable="vm.sortableOptions">
```

And I am initializing the Options as bellow:
```java
this.sortableOptions = {
    disabled: true
};
```

In my controller in angular after I set the `this.sortableOptions.disabled` to false the sortable feature is not being enabled.

The JqueryUI sortable has a `enable()` method, I may could use it somehow?

How to achieve the expected behavior?

**Comment by thgreasi** [comment]
Normally changes to the options are propagated to the jquery-ui widget.
What version are you using? Could you fork one of the provided code-pen examples found in README?
A way to retrieve the jquery ui widget object in order to call such methods is to do something like `$('myCssSelector').data('ui-sortable').refresh();` .

**Comment by thgreasi** [comment]
[Here is an example codepen](http://codepen.io/thgreasi/pen/aZdRwp) with the latest version.
Feel free to re-open if necessary.
