### ISSUE TITLE
Unexpected behaviour with jQuery 3.0.0

### ISSUE THREAD

**Issue by seriousjelly** [angular-ui/ui-sortable#465]
Strange behaviour when dragging and drop, items either bounce back, other items are moved around or item is placed in an incorrect place. 

jQuery 3.0.0

**Comment by thgreasi** [comment]
From [jQuery blog v3.0 announcement post](http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/):
> While most things will work, there are a few issues that jQuery UI and jQuery Mobile will be addressing in upcoming releases.

I will start experimenting with v3.0.

**Comment by chrisbratherton** [comment]
Great! 

Just thought that I'd share this with you as when I ran bower install Jquery auto updated to 3 which obviously caused sortable to stop working, spent the past hour or so head scratching!

**Comment by thgreasi** [comment]
Thanks for the heads-up. Didn't notice that v3.0 was already out!

**Comment by thgreasi** [comment]
I should probably also change the `bower.json` dependencies....

**Comment by chrisbratherton** [comment]
No worries.

**Comment by thgreasi** [comment]
Released v0.14.3 that avoids jquery v3 untill we can get proper support.

**Comment by rashmim00** [comment]
Version 0.1.4.3 doesn't work well with JQuery 3.1. Same behavior as outlined by Chris persists.

**Comment by thgreasi** [comment]
Haven't found enough time for this during the summer (I was getting married). I hope I will be able to start working on this soon.

**Comment by rashmim00** [comment]
Congratulations and I do hope you find time to start this.

**Comment by thgreasi** [comment]
The current source code seems to [work with jQuery v3.1 & jQuery-UI v1.12](codepen.io/thgreasi/pen/ORvLBa) without any change.
Moreover [all test cases pass](https://travis-ci.org/angular-ui/ui-sortable/builds/166043186).
Can anybody confirm that it works for you as well?

I guess that it might be an incompatibility between some versions of jQuery v3 & jQuery-UI, so I'm thinking about releasing v0.15.0 that demands jQuery v3.1.x & jQuery-UI v1.12.x . I'm skipping jQuery v3.0 in purpose, since it lived for just a week before v3.1 was released because of some issues and I think that people should avoid it as well.

As soon as someone confirms this, we can release v0.15.x and close this issue.

**Comment by thgreasi** [comment]
Closing this after releasing v1.5.0, where all tests pass with jQuery v3.1 and jQuery-UI v1.12.
Please re-open in any case.
