### ISSUE TITLE
Connected lists dropping not in dropzone still adds to dropzone

### ISSUE THREAD

**Issue by DrowningElysium** [angular-ui/ui-sortable#479]
We have 3 lists, one is for categories and the other is for items. Then these can be dropped inside the last one to create a checklist. The problem is that when a user goes over this dropzone and then drops it next to it. The system doesn't recognise this as a cancel operation. 

![image](https://cloud.githubusercontent.com/assets/9342313/17168109/c654ac76-53e0-11e6-8eb8-40f52725059c.png)

On the left is this dropzone. on the right are the lists for items and categories. First you need a category on the left to drop items in it.

I just can't find out if it is something we are doing wrong or that the plug-in doesn't support it.

**Comment by thgreasi** [comment]
Could you fork one of the codepen examples found in README.md to create a simplified version of your code? Otherwise it's very difficult to make assumptions and suggestions based on the provided description.

**Comment by DrowningElysium** [comment]
If you could come on gitter, we can give you access to the system as it is not live yet

**Comment by thgreasi** [comment]
The issue was that when an element was dragged outside of the draggable-sortable, the ui-sortable got a 0 height and as a result you can't place it back in its original place.

Suggested solutions:
1) define a minimum height for the draggable containers or
2) use placeholder option and define a height or
3) use the start & stop callbacks to
  * onDragStart:
    i) get the height of the dragged item
    ii) set that height to the draggable container
  * onDragStop set the height of the draggable container back to 'auto'
