### ISSUE TITLE
Exclude items in ui-sortable

### ISSUE THREAD

**Issue by mparisi76** [angular-ui/ui-sortable#78]
Hi, this may just be a feature request, not sure. I know that using jQuery, the ability to exclude items in a sortable array exists. Is there currently a way to do this using ui-sortable?

Thanks!

**Comment by benfoster** [comment]
I've tried this and it does not work for me. We want to prevent the first item from being dragged. Furthermore it is not in the array bound to the list (it's just a button). Since the index returned from `ui.item.index()` appears to be that of the DOM element, the index we send is always n+1

**Comment by thgreasi** [comment]
> Furthermore it is not in the array bound to the list (it's just a button).

README clearly states that:
> ui-sortable element should only contain one ng-repeat and not any other elements (above or below).
Otherwise the index matching of the generated DOM elements and the ng-model's items will break.
In other words: The items of ng-model must match the indexes of the generated DOM elements.

And then continues:
> ui-sortable lists containing many 'types' of items can be implemented by using dynamic template loading with ng-include or a loader directive, to determine how each model item should be rendered. Also take a look at the Tree with dynamic template example.

Obviously, a button is not semantically part of a list (except perhaps from the case that it is a list of buttons). Since using `types` of elements sounds like an overkill for your car, I would suggest you to wrap your sortable element with an extra div to house your button.
